---
- hosts: all
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: i want to install webserver
    apt:
      name: apache2
      state: present
    notify: restartwebserver

  - name: i want to copy my file in to ubuntu nodes
    template:
       src: myindex.j2
       dest: /var/www/html/index.html
    notify: restartwebserver

      
  handlers: 
     - name: restartwebserver
       service:
         name: apache2
         state: restarted