---
- hosts: mywebservers
  become: yes
  tasks: 
  - name: i want to install tree on ubuntu node
    apt: 
      name: "{{mytreepackageforubuntu}}"
      state: present
    when: ansible_os_family== "Debian"

  - name: i want to install wget on ubuntu node
    apt:  
      name: "{{mywgetpackageforubuntu}}"
      state: present
    when: ansible_os_family== "Debian"

        
