---
- hosts: all
  become: yes
  tasks:
  - name: i want to install web server on ubuntu node
    apt:
      name: "{{mywbpackageforubuntu}}"
      state: present

    when: ansible_os_family =="Debian"

  - name: i want to start webserver on ubuntu node
    service:
      name: "{{mywbpackageforubuntu}}"
      state: started

    when: ansible_os_family =="Debian"

  - name: i want to install webserver on RedHat node
    yum:  
      name: "{{mywebpackegeforRedHat}}" 
      state: present   
    when: ansible_os_family =="RedHat"

  - name: i want to to start webserver on RedHat node
    service:
      name: "{{mywebpackegeforRedHat}}"
      state: started   

    when: ansible_os_family =="RedHat"   

  - name: i want to install Java onubuntu node
    apt:
      name: "{{myjavapackageforubuntu}}"  
      state: present

    when: ansible_os_family =="Debian"

  - name: i want to install java on RedHat node
    yum:
      name: "{{myjavapackageforRedHat}}"
      state: present
       
    when: ansible_os_family =="RedHat" 

