---
- hosts: all
  become: yes
  tasks:
  - name: i want to install web server on ubuntu node
    apt:
      name: apache2
      state: present

  - name: i want to start webserver on ubuntu node
    service:
      name: apache2
      state: started

  - name: i want to install webserver on RedHat node
    yum:  
      name: httpd 
      state: present   

  - name: i want to to start webserver on RedHat node
    service:
      name: httpd
      state: started     

