---
- hosts: mywebservers
  become: yes
  tasks:
  - name: i want to install webserver on ubuntu node
    apt:
      name: "{{mywebpackforubuntu}}"
      state: present

    when: ansible_os_family =="Debian"

  - name: i want to start webserver on ubuntu node
    service:
      name: "{{mywebpackforubuntu}}"
      state: started
    when: ansible_os_family =="Debian"

  - name: i want to install webserver on amazon node
    yum:
      name: "{{mywebpackforRedHat}}"
      state: present

    when: ansible_os_family =="RedHat"
  - name: i want to start webserver on amazon node
    service:
      name: "{{mywebpackforRedHat}}"
      state: started    
    when: ansible_os_family =="RedHat"

